### ISSUE TITLE
[BE] Service to "clean" roles

### ISSUE THREAD

**Issue by pi0neerpat** [pi0neerpat/swordy-bot-v2#17]
### Background

- Admins are requesting user's roles to be removed when they no longer have the proper tokens (or lock expires)
- Should be automated, no manual process

### Tasks

- [ ] Create a new service `cleanServer` which accepts a server ID argument
- [ ] Can only be called by server admin (there is code for this already being used on some of the services)
- [ ] Service should map over ever role for every user. If we hit the timeout limit (60s for vercel?) we may need to discuss a better method here.
- [ ] If the user no longer has the correct tokens, remove the role
